
import React, { useState, useRef, useEffect } from 'react';
import { Upload, Settings2, PlayCircle, Download, Image as ImageIcon, CheckCircle2, Loader2, Scissors } from 'lucide-react';

interface GcodeSettings {
  width: number;
  feedRate: number;
  zSafe: number;
  zDepth: number;
  resolution: number; // Lines per mm
  invert: boolean;
  threshold: number; // For black/white binary
  mode: 'grayscale' | 'binary';
}

interface ImageToGcodeProps {
  onSendGcode: (gcode: string[]) => void;
}

export const ImageToGcode: React.FC<ImageToGcodeProps> = ({ onSendGcode }) => {
  const [image, setImage] = useState<string | null>(null);
  const [settings, setSettings] = useState<GcodeSettings>({
    width: 50,
    feedRate: 1000,
    zSafe: 2,
    zDepth: -0.5,
    resolution: 2,
    invert: false,
    threshold: 128,
    mode: 'binary'
  });
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedGcode, setGeneratedGcode] = useState<string[]>([]);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (event) => {
        setImage(event.target?.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const generateGcode = async () => {
    if (!image || !canvasRef.current) return;
    setIsGenerating(true);
    setGeneratedGcode([]);

    const canvas = canvasRef.current;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const img = new Image();
    img.src = image;
    await new Promise((resolve) => (img.onload = resolve));

    // Calculate dimensions
    const aspectRatio = img.height / img.width;
    const heightMm = settings.width * aspectRatio;
    
    // Set canvas resolution based on settings (lines per mm)
    canvas.width = settings.width * settings.resolution;
    canvas.height = heightMm * settings.resolution;
    
    ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
    const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
    const data = imageData.data;

    const gcode: string[] = [];
    gcode.push('; Image to G-code generated by CNC Pro');
    gcode.push('G21 ; Units: mm');
    gcode.push('G90 ; Absolute positioning');
    gcode.push(`G0 Z${settings.zSafe} F300 ; Move to safe Z`);

    const pixelWidth = canvas.width;
    const pixelHeight = canvas.height;
    const mmPerPixel = 1 / settings.resolution;

    for (let y = 0; y < pixelHeight; y++) {
      const yMm = (pixelHeight - y) * mmPerPixel; // Invert Y for CNC coordinates
      let isPenDown = false;

      // Move to start of line
      gcode.push(`G0 X0 Y${yMm.toFixed(3)}`);

      for (let x = 0; x < pixelWidth; x++) {
        const idx = (y * pixelWidth + x) * 4;
        const r = data[idx];
        const g = data[idx + 1];
        const b = data[idx + 2];
        const brightness = (r + g + b) / 3;
        
        const xMm = x * mmPerPixel;
        const finalBrightness = settings.invert ? 255 - brightness : brightness;

        if (settings.mode === 'binary') {
          const shouldEngrave = finalBrightness < settings.threshold;
          if (shouldEngrave && !isPenDown) {
            gcode.push(`G1 Z${settings.zDepth} F${settings.feedRate}`);
            isPenDown = true;
          } else if (!shouldEngrave && isPenDown) {
            gcode.push(`G0 Z${settings.zSafe}`);
            isPenDown = false;
          }
          if (shouldEngrave || isPenDown) {
            gcode.push(`G1 X${xMm.toFixed(3)} F${settings.feedRate}`);
          }
        } else {
          // Grayscale mode - map brightness to depth
          const depth = (1 - (finalBrightness / 255)) * settings.zDepth;
          gcode.push(`G1 X${xMm.toFixed(3)} Z${depth.toFixed(3)} F${settings.feedRate}`);
        }
      }

      // Ensure pen is up at end of line
      if (isPenDown) {
        gcode.push(`G0 Z${settings.zSafe}`);
      }
    }

    gcode.push(`G0 Z${settings.zSafe}`);
    gcode.push('G0 X0 Y0 ; Return to origin');
    gcode.push('M30 ; Program end');

    setGeneratedGcode(gcode);
    setIsGenerating(false);
  };

  const downloadGcode = () => {
    const blob = new Blob([generatedGcode.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'engraving.nc';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-col gap-6 pb-12">
      {/* Upload Section */}
      <div 
        onClick={() => fileInputRef.current?.click()}
        className={`relative h-48 border-2 border-dashed rounded-[2.5rem] flex flex-col items-center justify-center transition-all cursor-pointer overflow-hidden ${
          image ? 'border-blue-500/50 bg-blue-500/5' : 'border-slate-800 bg-slate-900/40 hover:border-slate-700'
        }`}
      >
        <input 
          type="file" 
          ref={fileInputRef} 
          onChange={handleImageUpload} 
          accept="image/*" 
          className="hidden" 
        />
        {image ? (
          <>
            <img src={image} className="absolute inset-0 w-full h-full object-contain opacity-30 grayscale" alt="Preview" />
            <div className="z-10 flex flex-col items-center">
              <CheckCircle2 size={32} className="text-blue-400 mb-2" />
              <span className="text-xs font-bold text-blue-400 uppercase">Image Loaded</span>
            </div>
          </>
        ) : (
          <>
            <Upload size={32} className="text-slate-600 mb-2" />
            <span className="text-xs font-bold text-slate-500 uppercase">Tap to upload Image</span>
          </>
        )}
      </div>

      {/* Settings Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="bg-slate-900/80 rounded-3xl p-6 border border-slate-800 space-y-4">
          <div className="flex items-center gap-2 mb-2">
            <Settings2 size={16} className="text-blue-400" />
            <span className="text-[10px] font-bold uppercase text-slate-500">Geometry</span>
          </div>
          
          <div className="space-y-3">
            <SettingRow label="Width (mm)" value={settings.width} min={1} max={500} step={1} onChange={(v) => setSettings(s => ({...s, width: v}))} />
            <SettingRow label="Resolution (L/mm)" value={settings.resolution} min={0.5} max={10} step={0.5} onChange={(v) => setSettings(s => ({...s, resolution: v}))} />
          </div>
        </div>

        <div className="bg-slate-900/80 rounded-3xl p-6 border border-slate-800 space-y-4">
          <div className="flex items-center gap-2 mb-2">
            <Scissors size={16} className="text-rose-400" />
            <span className="text-[10px] font-bold uppercase text-slate-500">Z-Axis & Feed</span>
          </div>
          
          <div className="space-y-3">
            <SettingRow label="Feedrate" value={settings.feedRate} min={100} max={5000} step={100} onChange={(v) => setSettings(s => ({...s, feedRate: v}))} />
            <SettingRow label="Z-Depth" value={settings.zDepth} min={-10} max={0} step={0.1} onChange={(v) => setSettings(s => ({...s, zDepth: v}))} />
            <SettingRow label="Z-Safe" value={settings.zSafe} min={0.5} max={20} step={0.5} onChange={(v) => setSettings(s => ({...s, zSafe: v}))} />
          </div>
        </div>
      </div>

      {/* Processing Modes */}
      <div className="bg-slate-900/80 rounded-3xl p-6 border border-slate-800">
        <div className="flex items-center gap-2 mb-4">
          <ImageIcon size={16} className="text-emerald-400" />
          <span className="text-[10px] font-bold uppercase text-slate-500">Conversion Mode</span>
        </div>
        <div className="flex gap-2 p-1 bg-slate-950 rounded-2xl border border-slate-800 mb-4">
          {(['binary', 'grayscale'] as const).map(m => (
            <button
              key={m}
              onClick={() => setSettings(s => ({...s, mode: m}))}
              className={`flex-1 py-3 rounded-xl text-xs font-bold uppercase transition-all ${
                settings.mode === m ? 'bg-blue-600 text-white shadow-lg' : 'text-slate-500'
              }`}
            >
              {m}
            </button>
          ))}
        </div>
        {settings.mode === 'binary' && (
          <SettingRow label="Threshold" value={settings.threshold} min={0} max={255} step={1} onChange={(v) => setSettings(s => ({...s, threshold: v}))} />
        )}
        <div className="mt-4 flex items-center justify-between">
           <span className="text-xs font-bold text-slate-500 uppercase">Invert Image</span>
           <button 
             onClick={() => setSettings(s => ({...s, invert: !s.invert}))}
             className={`w-12 h-6 rounded-full transition-all relative ${settings.invert ? 'bg-blue-600' : 'bg-slate-800'}`}
           >
             <div className={`absolute top-1 w-4 h-4 bg-white rounded-full transition-all ${settings.invert ? 'left-7' : 'left-1'}`} />
           </button>
        </div>
      </div>

      {/* Actions */}
      <div className="flex flex-col gap-3">
        <button 
          disabled={!image || isGenerating}
          onClick={generateGcode}
          className="w-full py-5 bg-blue-600 disabled:bg-slate-800 disabled:text-slate-600 text-white rounded-[2rem] font-black uppercase tracking-widest shadow-xl shadow-blue-900/20 active:scale-95 transition-all flex items-center justify-center gap-3"
        >
          {isGenerating ? <Loader2 className="animate-spin" /> : <PlayCircle />}
          {isGenerating ? 'Converting...' : 'Generate G-Code'}
        </button>

        {generatedGcode.length > 0 && (
          <div className="grid grid-cols-2 gap-3 animate-in fade-in slide-in-from-bottom-2">
             <button 
               onClick={() => onSendGcode(generatedGcode)}
               className="py-4 bg-emerald-600/20 text-emerald-400 border border-emerald-500/20 rounded-2xl font-bold text-sm flex items-center justify-center gap-2 active:scale-95 transition-all"
             >
               <PlayCircle size={18} /> Execute
             </button>
             <button 
               onClick={downloadGcode}
               className="py-4 bg-slate-800 text-slate-200 rounded-2xl font-bold text-sm flex items-center justify-center gap-2 active:scale-95 transition-all"
             >
               <Download size={18} /> Save .NC
             </button>
          </div>
        )}
      </div>

      {/* Hidden processing canvas */}
      <canvas ref={canvasRef} className="hidden" />
    </div>
  );
};

const SettingRow: React.FC<{ label: string; value: number; min: number; max: number; step: number; onChange: (v: number) => void }> = ({ label, value, min, max, step, onChange }) => (
  <div className="space-y-1">
    <div className="flex justify-between text-[10px] font-bold text-slate-400 uppercase">
      <span>{label}</span>
      <span className="text-white font-mono">{value}</span>
    </div>
    <input 
      type="range" 
      min={min} 
      max={max} 
      step={step} 
      value={value} 
      onChange={(e) => onChange(parseFloat(e.target.value))} 
      className="w-full h-1 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-blue-500"
    />
  </div>
);
